const SECRET_WORDS = [
    // ==================== 500 WORDS, PHRASES, PROVERBS, BOOKS & MOVIES ====================
    
    // --- 1-50: Words (A-L) ---
    { word: "ABHOR", hint: "To hate or detest intensely" },
    { word: "ACCLIMATE", hint: "To become accustomed to a new climate or situation" },
    { word: "ADROIT", hint: "Skillful and clever in handling tasks" },
    { word: "AFFLUENT", hint: "Having a great deal of money or wealth" },
    { word: "AGGRAVATE", hint: "To make a problem worse or more serious" },
    { word: "ALTRUISTIC", hint: "Unselfishly concerned for the welfare of others" },
    { word: "AMBIGUOUS", hint: "Open to more than one interpretation" },
    { word: "ANALOGOUS", hint: "Comparable in certain respects" },
    { word: "ANTAGONIZE", hint: "To cause someone to become hostile" },
    { word: "APATHETIC", hint: "Showing no interest, enthusiasm, or concern" },
    { word: "APPREHENSIVE", hint: "Anxious or fearful about the future" },
    { word: "ARBITRARY", hint: "Based on random choice rather than reason" },
    { word: "ARTICULATE", hint: "Able to express oneself clearly and effectively" },
    { word: "AUDACIOUS", hint: "Showing a willingness to take surprisingly bold risks" },
    { word: "AUTHORITARIAN", hint: "Demanding total obedience; dictatorial" },
    { word: "BANAL", hint: "So lacking in originality as to be obvious and boring" },
    { word: "BOISTEROUS", hint: "Noisy, energetic, and cheerful; rowdy" },
    { word: "BUREAUCRATIC", hint: "Relating to a system of government with many rules" },
    { word: "CANDID", hint: "Truthful and straightforward; frank" },
    { word: "CAPRICIOUS", hint: "Given to sudden and unaccountable changes of mood" },
    { word: "CAUSTIC", hint: "Sarcastic in a scathing and bitter way" },
    { word: "CHRONIC", hint: "Persisting for a long time or constantly recurring" },
    { word: "COERCIVE", hint: "Using force or threats to persuade someone" },
    { word: "COGNIZANT", hint: "Having knowledge or being aware of something" },
    { word: "COMPLACENT", hint: "Satisfied with oneself, unaware of danger" },
    { word: "CONCISE", hint: "Giving much information clearly in a few words" },
    { word: "CONDESCENDING", hint: "Behaving as if you are superior to others" },
    { word: "CONSPICUOUS", hint: "Clearly visible; attracting attention" },
    { word: "CONTRADICTORY", hint: "Mutually opposed or inconsistent" },
    { word: "COURTEOUS", hint: "Polite, respectful, and considerate" },
    { word: "CREDIBLE", hint: "Able to be believed; convincing" },
    { word: "CRITERION", hint: "A principle or standard by which something is judged" },
    { word: "CURSORY", hint: "Hasty and therefore not thorough" },
    { word: "DEBONAIR", hint: "Confident, stylish, and charming" },
    { word: "DEFERENCE", hint: "Respectful submission to the opinions of others" },
    { word: "DELIBERATE", hint: "Done on purpose; intentional" },
    { word: "DEPRECATE", hint: "To express disapproval of something" },
    { word: "DESOLATE", hint: "Deserted and barren; feeling abandoned" },
    { word: "DETACHED", hint: "Separate or disconnected; aloof and objective" },
    { word: "DEXTEROUS", hint: "Showing neat and skillful use of the hands" },
    { word: "DICHOTOMY", hint: "A division or contrast between two things" },
    { word: "DIDACTIC", hint: "Intended to teach, often in an instructional way" },
    { word: "DIFFIDENT", hint: "Modest or shy because of a lack of confidence" },
    { word: "DILETTANTE", hint: "A person who engages in a field without serious commitment" },
    { word: "DISCERNING", hint: "Having or showing good judgment" },
    { word: "DISDAIN", hint: "The feeling that someone is beneath you" },
    { word: "DISMAL", hint: "Causing sadness or gloom; very bad" },
    { word: "DISPARAGE", hint: "To criticize or belittle someone or something" },
    { word: "DISPOSITION", hint: "A person's natural mood or character" },
    { word: "DIVERGENT", hint: "Tending to be different or develop in different directions" },
    
    // --- 51-100: Words (M-Z) ---
    { word: "EBULLIENT", hint: "Cheerful and full of energy" },
    { word: "ECLECTIC", hint: "Deriving ideas from a broad range of sources" },
    { word: "EFFICACIOUS", hint: "Successful in producing a desired result" },
    { word: "EGREGIOUS", hint: "Outstandingly bad; shocking" },
    { word: "ELOQUENT", hint: "Fluent or persuasive in speaking or writing" },
    { word: "EMPHATIC", hint: "Expressed with force and conviction" },
    { word: "ENIGMATIC", hint: "Difficult to interpret or understand; mysterious" },
    { word: "EPICUREAN", hint: "Devoted to the pursuit of pleasure" },
    { word: "EQUANIMITY", hint: "Mental calmness and composure" },
    { word: "ERRATIC", hint: "Unpredictable; irregular in behavior" },
    { word: "ESOTERIC", hint: "Intended for or likely to be understood by a few" },
    { word: "EUPHEMISM", hint: "A mild or indirect word substituted for a harsh one" },
    { word: "EXASPERATE", hint: "To irritate or annoy extremely" },
    { word: "EXEMPLARY", hint: "Serving as a desirable model; perfect" },
    { word: "EXPLICIT", hint: "Stated clearly and in detail, leaving no room for confusion" },
    { word: "EXTRICATE", hint: "To free someone from a difficult situation" },
    { word: "FABRICATE", hint: "To invent or construct something, often falsely" },
    { word: "FACILITATE", hint: "To make a process easier or smoother" },
    { word: "FALLACIOUS", hint: "Based on a mistaken belief; misleading" },
    { word: "FANATICAL", hint: "Marked by extreme and unreasoning enthusiasm" },
    { word: "FASTIDIOUS", hint: "Very attentive to and concerned about accuracy and detail" },
    { word: "FEROCIOUS", hint: "Savagely fierce, cruel, or violent" },
    { word: "FERVENT", hint: "Having or displaying passionate intensity" },
    { word: "FICKLE", hint: "Changing frequently in mood or loyalty" },
    { word: "FLAGRANT", hint: "Conspicuously and outrageously bad" },
    { word: "FORBEARANCE", hint: "Patient self-control; restraint" },
    { word: "FORTUITOUS", hint: "Happening by chance, especially with a favorable outcome" },
    { word: "FRIVOLOUS", hint: "Not having any serious purpose or value" },
    { word: "FURTIVE", hint: "Attempting to avoid notice; secretive" },
    { word: "GARRULOUS", hint: "Excessively talkative, especially on trivial matters" },
    { word: "GREGARIOUS", hint: "Sociable; enjoying the company of others" },
    { word: "HAPHAZARD", hint: "Lacking any obvious plan or order" },
    { word: "HEDONISM", hint: "The pursuit of pleasure as the highest good" },
    { word: "HETEROGENEOUS", hint: "Consisting of different kinds of parts" },
    { word: "HOMOGENEOUS", hint: "Consisting of parts all of the same kind" },
    { word: "HYPOTHETICAL", hint: "Based on a suggested idea; not proven" },
    { word: "IDIOSYNCRATIC", hint: "Peculiar to an individual; unique" },
    { word: "IMBUE", hint: "To inspire or permeate with a feeling or quality" },
    { word: "IMMACULATE", hint: "Perfectly clean, neat, or pure" },
    { word: "IMMUTABLE", hint: "Unchanging over time; unchangeable" },
    { word: "IMPARTIAL", hint: "Treating all equally; unbiased" },
    { word: "IMPEDE", hint: "To slow down or obstruct the progress of something" },
    { word: "IMPETUOUS", hint: "Acting quickly without thought or care" },
    { word: "IMPLEMENT", hint: "To put a plan or decision into effect" },
    { word: "IMPLICIT", hint: "Implied though not directly stated" },
    { word: "INADVERTENT", hint: "Not resulting from a planned or deliberate action" },
    { word: "INANIMATE", hint: "Not alive; without life" },
    { word: "INDEFATIGABLE", hint: "Persisting tirelessly; unstoppable" },
    { word: "INDEPENDENT", hint: "Free from outside control; self-reliant" },
    { word: "INDIGENT", hint: "Poor; lacking basic necessities" },
    { word: "INDIGNANT", hint: "Feeling anger at unfair treatment" },
    { word: "INDUBITABLE", hint: "Without doubt; unquestionable" },
    { word: "INEVITABLE", hint: "Certain to happen; unavoidable" },
    { word: "INEXORABLE", hint: "Impossible to stop or prevent" },
    { word: "INFAMOUS", hint: "Well known for some bad quality or deed" },
    { word: "INGENIOUS", hint: "Clever, original, and inventive" },
    { word: "INHERENT", hint: "Existing in something as a permanent quality" },
    { word: "INNOVATIVE", hint: "Featuring new methods; advanced and original" },
    { word: "INQUISITIVE", hint: "Curious; tending to ask questions" },
    { word: "INSIDIOUS", hint: "Proceeding in a gradual way but with harmful effects" },
    { word: "INSOLENT", hint: "Showing rude and arrogant behavior" },
    { word: "INSPECT", hint: "To examine carefully and critically" },
    { word: "INSTANTANEOUS", hint: "Occurring or done in an instant" },
    { word: "INSULIN", hint: "A hormone that regulates blood sugar" },
    { word: "INTEGRITY", hint: "The quality of being honest and having strong moral principles" },
    { word: "INTERMITTENT", hint: "Occurring at irregular intervals; not continuous" },
    { word: "INTREPID", hint: "Fearless; adventurous" },
    { word: "INTRICATE", hint: "Having many complexly arranged elements" },
    { word: "INTRINSIC", hint: "Belonging naturally; essential" },
    { word: "INVALUABLE", hint: "Extremely useful; indispensable" },
    { word: "INVESTIGATE", hint: "To carry out a systematic inquiry" },
    { word: "IRRELEVANT", hint: "Not connected to the matter at hand" },
    { word: "IRREVOCABLE", hint: "Not able to be changed or reversed" },
    { word: "JOCUND", hint: "Cheerful and lighthearted" },
    { word: "JUDICIOUS", hint: "Having or showing good sense and judgment" },
    { word: "JUVENILE", hint: "Relating to youth; childish or immature" },
    { word: "KALEIDOSCOPIC", hint: "Changing patterns of colors and shapes" },
    { word: "KINETIC", hint: "Relating to motion or movement" },
    { word: "LACERATE", hint: "To tear or cut deeply" },
    { word: "LAMENT", hint: "A passionate expression of grief or sorrow" },
    { word: "LASCIVIOUS", hint: "Feeling or showing lustful desire" },
    { word: "LAUDABLE", hint: "Deserving praise and commendation" },
    { word: "LEGITIMATE", hint: "Conforming to the law; lawful" },
    { word: "LETHARGY", hint: "A state of sluggishness or lack of energy" },
    { word: "LITIGATE", hint: "To engage in a legal dispute" },
    { word: "LOQUACIOUS", hint: "Tending to talk a great deal; talkative" },
    { word: "LUGUBRIOUS", hint: "Looking or sounding sad and mournful" },

    // --- 101-150: Words (M-Z continued) ---
    { word: "MALEVOLENT", hint: "Having or showing a wish to do evil to others" },
    { word: "MALIGN", hint: "To speak evil of; harmful in nature" },
    { word: "MANIFEST", hint: "Clear or obvious to the eye or mind" },
    { word: "MELANCHOLY", hint: "A feeling of deep sadness or sorrow" },
    { word: "MENDACIOUS", hint: "Untruthful; given to lying" },
    { word: "MERCURIAL", hint: "Subject to sudden or unpredictable changes of mood" },
    { word: "METICULOUS", hint: "Showing great attention to detail" },
    { word: "MISANTHROPE", hint: "A person who dislikes people in general" },
    { word: "MITIGATE", hint: "To make less severe or painful" },
    { word: "MOROSE", hint: "Sullen and ill-tempered" },
    { word: "MUNDANE", hint: "Lacking interest; ordinary and boring" },
    { word: "MUTABLE", hint: "Likely to change; variable" },
    { word: "NARCISSISTIC", hint: "Excessive interest in oneself" },
    { word: "NEBULOUS", hint: "Vague, unclear, or ill-defined" },
    { word: "NEGLIGENT", hint: "Failing to take proper care in doing something" },
    { word: "NEPOTISM", hint: "Favoritism shown to friends or family by those in power" },
    { word: "NOXIOUS", hint: "Harmful, poisonous, or offensive" },
    { word: "NUANCE", hint: "A subtle difference in meaning or expression" },
    { word: "OBFUSCATE", hint: "To deliberately make something unclear" },
    { word: "OBLIVIOUS", hint: "Not aware of or not concerned about what is happening" },
    { word: "OBSCURE", hint: "Not well known; difficult to understand" },
    { word: "OBSESSIVE", hint: "Characterized by persistent preoccupation" },
    { word: "OBSTINATE", hint: "Refusing to change one's opinion or course of action" },
    { word: "OFTEN", hint: "Frequently; many times" },
    { word: "OPPRESSIVE", hint: "Unjustly burdensome; harsh" },
    { word: "OPULENT", hint: "Rich, luxurious, or lavish" },
    { word: "ORTHODOX", hint: "Following traditional or established beliefs" },
    { word: "OSTENTATIOUS", hint: "Characterized by vulgar or pretentious display" },
    { word: "PALLIATE", hint: "To make a problem less severe without curing it" },
    { word: "PENURIOUS", hint: "Extremely stingy or poor" },
    { word: "PERFIDIOUS", hint: "Deceitful and untrustworthy" },
    { word: "PERNICIOUS", hint: "Having a harmful effect, especially in a gradual way" },
    { word: "PERTINENT", hint: "Relevant or applicable to a particular matter" },
    { word: "PESSIMISTIC", hint: "Tending to see the worst aspect of things" },
    { word: "PHENOMENAL", hint: "Remarkable or exceptional" },
    { word: "PHILANTHROPIC", hint: "Generous in helping the needy" },
    { word: "PIOUS", hint: "Deeply religious; devout" },
    { word: "PLAUSIBLE", hint: "Seeming reasonable or probable" },
    { word: "POLARIZE", hint: "To divide into two sharply contrasting groups" },
    { word: "POLLUTE", hint: "To contaminate the environment" },
    { word: "PRAGMATIC", hint: "Dealing with things sensibly and realistically" },
    { word: "PRECARIOUS", hint: "Not securely held; likely to fall" },
    { word: "PRECISE", hint: "Exact and accurate" },
    { word: "PREDICTABLE", hint: "Able to be foreseen or expected" },
    { word: "PREJUDICE", hint: "Preconceived opinion not based on reason" },
    { word: "PREMEDITATED", hint: "Planned or considered in advance" },
    { word: "PROFOUND", hint: "Very deep, intense, or meaningful" },
    { word: "PROLIFIC", hint: "Producing many works or results" },
    { word: "PROPAGATE", hint: "To spread or promote an idea widely" },
    { word: "PROVINCIAL", hint: "Of or concerning a province; unsophisticated" },
    { word: "PUGNACIOUS", hint: "Eager to fight or argue" },
    { word: "PUNCTILIOUS", hint: "Paying great attention to detail and rules" },
    { word: "QUAGMIRE", hint: "A difficult situation; a soft, boggy area" },
    { word: "QUERULOUS", hint: "Complaining in a whining manner" },
    { word: "QUIXOTIC", hint: "Excessively idealistic and unrealistic" },
    { word: "RABID", hint: "Having or showing an extreme, fanatical enthusiasm" },
    { word: "RANCOR", hint: "Bitter resentment or ill will" },
    { word: "RAREFIED", hint: "Distant from ordinary life; refined" },
    { word: "RATIONAL", hint: "Based on or in accordance with reason" },
    { word: "RECALCITRANT", hint: "Defiant of authority or control" },
    { word: "RECIPROCATE", hint: "To respond to an action or gesture with a similar one" },
    { word: "RECKLESS", hint: "Showing a lack of care about risks or consequences" },
    { word: "RECONDITE", hint: "Little known; abstruse or obscure" },
    { word: "REDUNDANT", hint: "Not or no longer needed; superfluous" },
    { word: "REFUTE", hint: "To prove a statement or theory to be wrong" },
    { word: "RELEGATE", hint: "To assign an inferior rank or position" },
    { word: "RELENTLESS", hint: "Showing no abatement of intensity; persistent" },
    { word: "RELEVANT", hint: "Connected to the matter at hand" },
    { word: "REMORSE", hint: "Deep regret for a wrong committed" },
    { word: "RENEGADE", hint: "A person who abandons a cause or group" },
    { word: "RESILIENT", hint: "Able to recover quickly from difficulties" },
    { word: "RESOLUTE", hint: "Determined and unwavering" },
    { word: "RESPITE", hint: "A short period of rest or relief" },
    { word: "RETICENT", hint: "Not revealing one's thoughts; reserved" },
    { word: "REVERE", hint: "To feel deep respect or awe for someone" },
    { word: "RIGOROUS", hint: "Extremely thorough and careful" },
    { word: "RUDIMENTARY", hint: "Basic or elementary; not fully developed" },
    { word: "RUSTIC", hint: "Relating to the countryside; simple and unsophisticated" },
    { word: "SAGACIOUS", hint: "Wise and shrewd in judgment" },
    { word: "SALIENT", hint: "Most noticeable or important" },
    { word: "SANGUINE", hint: "Optimistic or positive, especially in a difficult situation" },
    { word: "SCEPTICAL", hint: "Not easily convinced; doubting" },
    { word: "SERENDIPITY", hint: "Finding something good without looking for it" },
    { word: "SERVILE", hint: "Showing an excessive willingness to serve or please others" },
    { word: "SIGNIFICANT", hint: "Sufficiently great or important to be worthy of attention" },
    { word: "SINISTER", hint: "Giving the impression that something harmful or evil is happening" },
    { word: "SKEPTICAL", hint: "Not easily convinced; doubting" },
    { word: "SLUGGISH", hint: "Slow-moving or inactive" },
    { word: "SOPHISTICATED", hint: "Complex, refined, or highly developed" },
    { word: "SPURIOUS", hint: "Fake; not genuine" },
    { word: "STAGNANT", hint: "Lacking activity, development, or movement" },
    { word: "STALWART", hint: "Loyal, reliable, and hardworking" },
    { word: "STOIC", hint: "Enduring pain or hardship without complaint" },
    { word: "STRENUOUS", hint: "Requiring or involving great effort" },
    { word: "SUBTLE", hint: "So delicate or precise as to be difficult to analyze" },
    { word: "SUPERFICIAL", hint: "Appearing to be true but lacking depth" },
    { word: "SURREPTITIOUS", hint: "Kept secret, especially because it would not be approved" },
    { word: "SUSCEPTIBLE", hint: "Likely or liable to be influenced or harmed by something" },
    { word: "TACITURN", hint: "Reserved; saying little" },
    { word: "TANGIBLE", hint: "Perceptible by touch; real and concrete" },
    { word: "TENACIOUS", hint: "Holding firmly to a belief or purpose" },
    { word: "TENUOUS", hint: "Very weak or slight; flimsy" },
    { word: "TERSE", hint: "Sparing in the use of words; abrupt" },
    { word: "THOROUGH", hint: "Complete with regard to every detail" },
    { word: "TIMOROUS", hint: "Suffering from nervousness, fear, or lack of confidence" },
    { word: "TORRENT", hint: "A strong and fast-moving stream of water or other liquid" },
    { word: "TRANQUIL", hint: "Free from disturbance; calm" },
    { word: "TRANSIENT", hint: "Lasting only for a short time; impermanent" },
    { word: "TREPIDATION", hint: "Fear or anxiety about something that may happen" },
    { word: "TRITE", hint: "Overused and lacking originality" },
    { word: "UBIQUITOUS", hint: "Present, appearing, or found everywhere" },
    { word: "UNANIMOUS", hint: "Fully in agreement" },
    { word: "UNCONVENTIONAL", hint: "Not based on or conforming to what is generally done" },
    { word: "UNDERMINE", hint: "To lessen the effectiveness or authority of something" },
    { word: "UNPRECEDENTED", hint: "Never done or known before" },
    { word: "UNWIELDY", hint: "Difficult to move or handle due to size or shape" },
    { word: "URBANE", hint: "Courteous, refined, and suave" },
    { word: "USURP", hint: "To seize power or position illegally" },
    { word: "UTOPIAN", hint: "Modeled on or aiming for a state of perfection" },
    { word: "VACILLATE", hint: "Waver between different opinions or actions" },
    { word: "VENERABLE", hint: "Deserving respect due to age or wisdom" },
    { word: "VERBOSE", hint: "Using more words than needed; wordy" },
    { word: "VICISSITUDE", hint: "A change of circumstances, often unwelcome" },
    { word: "VINDICTIVE", hint: "Having a strong desire for revenge" },
    { word: "VORACIOUS", hint: "Eager to consume great amounts of food or knowledge" },
    { word: "WHIMSICAL", hint: "Playfully unpredictable or odd" },
    { word: "WISTFUL", hint: "Longing with a tinge of sadness" },
    { word: "XENOPHOBIA", hint: "Fear or hatred of foreigners or strangers" },
    { word: "YESTERYEAR", hint: "The past, especially a time long ago" },
    { word: "ZEALOT", hint: "A person who is fanatical and uncompromising" },

    // --- 151-200: Proverbs & Idioms (Part 1) ---
    { word: "A BIRD IN THE HAND IS WORTH TWO IN THE BUSH", hint: "Better to have a small certainty than a large possibility" },
    { word: "A FOOL AND HIS MONEY ARE SOON PARTED", hint: "Fools lose money quickly" },
    { word: "A LEOPARD CANNOT CHANGE ITS SPOTS", hint: "A person's character is unchangeable" },
    { word: "A LITTLE KNOWLEDGE IS A DANGEROUS THING", hint: "Partial knowledge can lead to mistakes" },
    { word: "A ROLLING STONE GATHERS NO MOSS", hint: "A person who keeps moving does not accumulate wealth or friends" },
    { word: "A STITCH IN TIME SAVES NINE", hint: "Fixing a problem early prevents it from getting worse" },
    { word: "A WATCHED POT NEVER BOILS", hint: "Time seems to pass slowly when you are waiting" },
    { word: "ABSENCE MAKES THE HEART GROW FONDER", hint: "Being apart makes you appreciate someone more" },
    { word: "ACTIONS SPEAK LOUDER THAN WORDS", hint: "What you do is more important than what you say" },
    { word: "ALL GOOD THINGS COME TO THOSE WHO WAIT", hint: "Patience is rewarded" },
    { word: "ALL THAT GLITTERS IS NOT GOLD", hint: "Appearances can be deceptive" },
    { word: "ALL WORK AND NO PLAY MAKES JACK A DULL BOY", hint: "Too much work without rest is unhealthy" },
    { word: "AN APPLE A DAY KEEPS THE DOCTOR AWAY", hint: "Eating healthy helps prevent illness" },
    { word: "APRIL SHOWERS BRING MAY FLOWERS", hint: "Rain in April leads to flowers in May" },
    { word: "AS THE TWIG IS BENT, THE TREE INCLINES", hint: "Early habits shape a person's future" },
    { word: "AS YOU SOW, SO SHALL YOU REAP", hint: "Your actions determine your consequences" },
    { word: "BARKING UP THE WRONG TREE", hint: "Mistakenly directing efforts at the wrong target" },
    { word: "BEGGARS CAN'T BE CHOOSERS", hint: "Those with no options must accept what they get" },
    { word: "BETTER LATE THAN NEVER", hint: "Better to arrive late than not at all" },
    { word: "BETTER SAFE THAN SORRY", hint: "Better to be cautious than to regret later" },
    { word: "BIRDS OF A FEATHER FLOCK TOGETHER", hint: "People with similar interests stick together" },
    { word: "BLOOD IS THICKER THAN WATER", hint: "Family ties are stronger than other relationships" },
    { word: "CLEANLINESS IS NEXT TO GODLINESS", hint: "Being clean is a moral virtue" },
    { word: "COLD FEET", hint: "Nervousness before an important event" },
    { word: "COUNT YOUR BLESSINGS", hint: "Be grateful for what you have" },
    { word: "CRY OVER SPILLED MILK", hint: "To be upset over something that cannot be undone" },
    { word: "CURIOSITY KILLED THE CAT", hint: "Prying into things can lead to trouble" },
    { word: "CUT CORNERS", hint: "To save time or effort by ignoring quality" },
    { word: "DISCRETION IS THE BETTER PART OF VALOR", hint: "Knowing when to avoid danger is courageous" },
    { word: "DO AS YOU WOULD BE DONE BY", hint: "Treat others as you want to be treated" },
    { word: "DON'T BITE THE HAND THAT FEEDS YOU", hint: "Don't harm those who help you" },
    { word: "DON'T COUNT YOUR CHICKENS BEFORE THEY HATCH", hint: "Don't assume success before it happens" },
    { word: "DON'T CROSS THE BRIDGE UNTIL YOU COME TO IT", hint: "Don't worry about problems before they happen" },
    { word: "DON'T JUDGE A BOOK BY ITS COVER", hint: "Do not judge by appearance alone" },
    { word: "DON'T PUT ALL YOUR EGGS IN ONE BASKET", hint: "Don't risk everything on one venture" },
    { word: "DON'T PUT THE CART BEFORE THE HORSE", hint: "Do things in the correct order" },
    { word: "DON'T THROW THE BABY OUT WITH THE BATHWATER", hint: "Don't discard something good while removing something bad" },
    { word: "DON'T WEAR OUT YOUR WELCOME", hint: "Don't overstay or outstay your welcome" },
    { word: "EASY COME, EASY GO", hint: "Things gained quickly are often lost quickly" },
    { word: "ELBOW GREASE", hint: "Hard physical effort or work" },
    { word: "EVERY CLOUD HAS A SILVER LINING", hint: "Every bad situation has a positive side" },
    { word: "EVERY DOG HAS ITS DAY", hint: "Everyone will have a lucky moment" },
    { word: "FAINT HEART NEVER WON FAIR LADY", hint: "Success requires courage and risk" },
    { word: "FAIR-WEATHER FRIEND", hint: "Someone who is only a friend when things are easy" },
    { word: "FOR BETTER OR FOR WORSE", hint: "In good times and bad" },
    { word: "FULL OF HOT AIR", hint: "Talkative but lacking substance" },
    { word: "GET THE SHORT END OF THE STICK", hint: "To receive less than one deserves" },
    { word: "GIVE THE DEVIL HIS DUE", hint: "Even enemies deserve fairness" },
    { word: "GO THE EXTRA MILE", hint: "Make more effort than expected" },
    { word: "GREAT MINDS THINK ALIKE", hint: "Smart people often have the same ideas" },

    // --- 201-250: Proverbs & Idioms (Part 2) ---
    { word: "HALF A LOAF IS BETTER THAN NONE", hint: "Having less than desired is still better than nothing" },
    { word: "HE WHO PAYS THE PIPER CALLS THE TUNE", hint: "The person who provides the money makes the decisions" },
    { word: "HINDSIGHT IS 20/20", hint: "Understanding past events is easier after they happen" },
    { word: "HOLD YOUR HORSES", hint: "Wait a moment; slow down" },
    { word: "HONESTY IS THE BEST POLICY", hint: "Telling the truth is the wisest approach" },
    { word: "HORSE OF A DIFFERENT COLOR", hint: "A different matter entirely" },
    { word: "IF IT AIN'T BROKE, DON'T FIX IT", hint: "Don't change something that already works" },
    { word: "IF YOU CAN'T STAND THE HEAT, GET OUT OF THE KITCHEN", hint: "Leave a difficult situation if you can't handle it" },
    { word: "IGNORANCE IS BLISS", hint: "Not knowing problems is a relief" },
    { word: "IN THE LAND OF THE BLIND, THE ONE-EYED MAN IS KING", hint: "A minor advantage can make you superior in a weak group" },
    { word: "IN THE NICK OF TIME", hint: "Just before it is too late" },
    { word: "IN THE SAME BOAT", hint: "In the same difficult situation" },
    { word: "IT NEVER RAINS BUT IT POURS", hint: "Bad things often happen all at once" },
    { word: "IT TAKES TWO TO TANGO", hint: "Both parties are needed for a situation" },
    { word: "JACK OF ALL TRADES, MASTER OF NONE", hint: "Good at many things, expert at none" },
    { word: "JUMP ON THE BANDWAGON", hint: "Join a trend or popular movement" },
    { word: "JUMP THE GUN", hint: "To act too soon or before the right time" },
    { word: "KEEP YOUR CHIN UP", hint: "Stay optimistic and strong" },
    { word: "KILL THE MESSENGER", hint: "To blame the one who brings bad news" },
    { word: "KILL TWO BIRDS WITH ONE STONE", hint: "To achieve two things with one action" },
    { word: "KNOWLEDGE IS POWER", hint: "Understanding gives you control" },
    { word: "LAUGHTER IS THE BEST MEDICINE", hint: "Humor heals stress and sadness" },
    { word: "LET BYGONES BE BYGONES", hint: "Forgive past wrongs and move on" },
    { word: "LET SLEEPING DOGS LIE", hint: "To not disturb a situation that is currently calm" },
    { word: "LET THE CAT OUT OF THE BAG", hint: "Reveal a secret by accident" },
    { word: "LIFE IS TOO SHORT TO WORRY ABOUT THE SMALL STUFF", hint: "Focus on what truly matters" },
    { word: "LIGHTNING NEVER STRIKES THE SAME PLACE TWICE", hint: "Unlikely events rarely repeat exactly" },
    { word: "LIVE AND LET LIVE", hint: "Be tolerant and allow others to live their way" },
    { word: "LOVE IS BLIND", hint: "Love does not see flaws in the beloved" },
    { word: "MAKE A LONG STORY SHORT", hint: "To summarize a longer story" },
    { word: "MAKE A MOUNTAIN OUT OF A MOLEHILL", hint: "Exaggerate a minor problem" },
    { word: "MISERY LOVES COMPANY", hint: "Unhappy people want others to share their misery" },
    { word: "MONEY CAN'T BUY HAPPINESS", hint: "Wealth does not guarantee joy" },
    { word: "MONEY DOESN'T GROW ON TREES", hint: "Money is not easily obtained" },
    { word: "MORE HASTE, LESS SPEED", hint: "Rushing leads to mistakes and delays" },
    { word: "NECESSITY IS THE MOTHER OF INVENTION", hint: "Problems create solutions" },
    { word: "NEVER BITE THE HAND THAT FEEDS YOU", hint: "Don't harm someone who helps you" },
    { word: "NEVER LOOK A GIFT HORSE IN THE MOUTH", hint: "Don't be critical of a gift" },
    { word: "NO MAN IS AN ISLAND", hint: "Everyone needs others to survive" },
    { word: "NO PAIN, NO GAIN", hint: "Effort and struggle are needed for success" },
    { word: "NO REST FOR THE WICKED", hint: "Bad people face constant trouble" },
    { word: "NO USE CRYING OVER SPILLED MILK", hint: "Don't be upset about something already done" },
    { word: "NOT ALL IT'S CRACKED UP TO BE", hint: "Not as good as expected" },
    { word: "OLD HABITS DIE HARD", hint: "Bad habits are difficult to break" },
    { word: "ONCE BITTEN, TWICE SHY", hint: "Past pain makes you cautious" },
    { word: "ONCE IN A BLUE MOON", hint: "Very rarely" },
    { word: "OPPORTUNITY KNOCKS ONLY ONCE", hint: "Don't miss a rare chance" },
    { word: "OUT OF SIGHT, OUT OF MIND", hint: "Things forgotten when not seen" },
    { word: "OUT OF THIS WORLD", hint: "Extremely good or amazing" },
    { word: "OUT ON A LIMB", hint: "In a risky or vulnerable position" },

    // --- 251-300: Proverbs & Idioms (Part 3) ---
    { word: "PATIENCE IS A VIRTUE", hint: "Waiting calmly is a good quality" },
    { word: "PEOPLE WHO LIVE IN GLASS HOUSES SHOULDN'T THROW STONES", hint: "Don't criticize others if you have flaws yourself" },
    { word: "PIECE OF CAKE", hint: "Something very easy to do" },
    { word: "PRACTICE MAKES PERFECT", hint: "Repeated effort leads to mastery" },
    { word: "PREVENTION IS BETTER THAN CURE", hint: "Stop problems before they start" },
    { word: "PROCRASTINATION IS THE THIEF OF TIME", hint: "Delaying tasks wastes valuable time" },
    { word: "PULL SOMEONE'S LEG", hint: "Tease or joke with someone" },
    { word: "PULL YOURSELF TOGETHER", hint: "To regain composure or control" },
    { word: "QUICK AS A FLASH", hint: "Extremely fast" },
    { word: "QUICK ON THE DRAW", hint: "Fast to react or respond" },
    { word: "QUIET WATERS RUN DEEP", hint: "Calm people often have deep thoughts" },
    { word: "RING A BELL", hint: "To sound familiar or remind someone of something" },
    { word: "RISE TO THE OCCASION", hint: "To perform well under pressure" },
    { word: "ROME WASN'T BUILT IN A DAY", hint: "Great things take time" },
    { word: "RUB SOMEONE THE WRONG WAY", hint: "Irritate or annoy someone" },
    { word: "SEE EYE TO EYE", hint: "To agree completely" },
    { word: "SHOT IN THE DARK", hint: "A wild guess or attempt" },
    { word: "SOFTLY, SOFTLY, CATCHEE MONKEY", hint: "Patience and care lead to success" },
    { word: "SPILL THE BEANS", hint: "Reveal secret information" },
    { word: "STILL WATERS RUN DEEP", hint: "Quiet people often have deep thoughts" },
    { word: "STRIKE WHILE THE IRON IS HOT", hint: "Act at the right moment" },
    { word: "TAKE A RAIN CHECK", hint: "To postpone an invitation" },
    { word: "THE BALL IS IN YOUR COURT", hint: "It is your turn to take action" },
    { word: "THE EARLY BIRD CATCHES THE WORM", hint: "Start early to gain an advantage" },
    { word: "THE END JUSTIFIES THE MEANS", hint: "Bad actions can be accepted if the result is good" },
    { word: "THE PEN IS MIGHTIER THAN THE SWORD", hint: "Words have more power than violence" },
    { word: "THE SHOE FITS, WEAR IT", hint: "If a criticism applies, accept it" },
    { word: "THE SKY IS THE LIMIT", hint: "There is no limit to what you can achieve" },
    { word: "THERE IS NO SMOKE WITHOUT FIRE", hint: "Rumors usually have some truth" },
    { word: "THOSE WHO LIVE BY THE SWORD, DIE BY THE SWORD", hint: "Violence leads to violent consequences" },
    { word: "TIME IS MONEY", hint: "Time is valuable" },
    { word: "TOO MANY COOKS SPOIL THE BROTH", hint: "Too many people ruin a task" },
    { word: "TRUTH IS STRANGER THAN FICTION", hint: "Reality can be more unusual than stories" },
    { word: "TURN A BLIND EYE", hint: "To ignore something deliberately" },
    { word: "UNDER THE WEATHER", hint: "Feeling ill or unwell" },
    { word: "UNDER YOUR BREATH", hint: "Speaking very softly or quietly" },
    { word: "UNITY IS STRENGTH", hint: "Together, people are stronger" },
    { word: "UP THE ANTE", hint: "To increase the stakes or risk" },
    { word: "VARIETY IS THE SPICE OF LIFE", hint: "Diversity makes life interesting" },
    { word: "VOICE IN THE WILDERNESS", hint: "A person who warns but is ignored" },
    { word: "WALK ON EGGSHELLS", hint: "Act with extreme caution around someone" },
    { word: "WE ARE ALL IN THE SAME BOAT", hint: "Everyone shares the same situation" },
    { word: "WHAT GOES AROUND COMES AROUND", hint: "Good or bad behavior returns to you" },
    { word: "WHEN IN ROME, DO AS THE ROMANS DO", hint: "Follow local customs" },
    { word: "WHERE THERE IS SMOKE, THERE IS FIRE", hint: "Signs of a problem usually mean one exists" },
    { word: "WHERE THERE'S A WILL, THERE'S A WAY", hint: "Determination overcomes obstacles" },
    { word: "WHISTLE FOR IT", hint: "To try to get something that is unlikely" },
    { word: "WILD GOOSE CHASE", hint: "A pointless or hopeless search" },
    { word: "X MARKS THE SPOT", hint: "The exact location of something" },
    { word: "YOU CAN'T HAVE YOUR CAKE AND EAT IT TOO", hint: "Cannot have two incompatible things" },
    { word: "YOU CAN'T TEACH AN OLD DOG NEW TRICKS", hint: "Older people find it hard to change" },

    // --- 301-350: Books & Novels ---
    { word: "A CHRISTMAS CAROL", hint: "A book about a miser who learns kindness" },
    { word: "A CLOCKWORK ORANGE", hint: "A dystopian novel about free will and violence" },
    { word: "A FAREWELL TO ARMS", hint: "A novel about love and war" },
    { word: "A GAME OF THRONES", hint: "A fantasy epic about power struggles" },
    { word: "A TALE OF TWO CITIES", hint: "A novel set during the French Revolution" },
    { word: "ALICE'S ADVENTURES IN WONDERLAND", hint: "A girl falls into a magical world" },
    { word: "ANIMAL FARM", hint: "Farm animals rebel against humans" },
    { word: "ANNA KARENINA", hint: "A tragic love story in Russian society" },
    { word: "BRAVE NEW WORLD", hint: "A dystopian future where society is controlled" },
    { word: "CATCH-22", hint: "A no-win situation with contradictory rules" },
    { word: "CRIME AND PUNISHMENT", hint: "A man commits murder and faces guilt" },
    { word: "DAVID COPPERFIELD", hint: "A young man's journey to adulthood" },
    { word: "DON QUIXOTE", hint: "A novel about a man who tilts at windmills" },
    { word: "DRACULA", hint: "A classic vampire novel" },
    { word: "EMMA", hint: "A novel about a young woman who matchmakes" },
    { word: "FAHRENHEIT 451", hint: "A dystopian novel where books are burned" },
    { word: "FRANKENSTEIN", hint: "A scientist creates a monster" },
    { word: "GONE WITH THE WIND", hint: "A love story set during the US Civil War" },
    { word: "GREAT EXPECTATIONS", hint: "A young man's rise from poverty to wealth" },
    { word: "HAMLET", hint: "A prince seeks revenge for his father's murder" },
    { word: "HEART OF DARKNESS", hint: "A journey into the Congo and human darkness" },
    { word: "IN THE HEART OF THE SEA", hint: "A true story of a whale attack" },
    { word: "INVISIBLE MAN", hint: "A scientist becomes invisible and goes mad" },
    { word: "JANE EYRE", hint: "A governess falls in love with her employer" },
    { word: "JULIUS CAESAR", hint: "A play about betrayal and assassination" },
    { word: "KILL A MOCKINGBIRD", hint: "A lawyer defends a black man in a racist town" },
    { word: "LADY WINDERMERE'S FAN", hint: "A play about infidelity and social gossip" },
    { word: "LITTLE WOMEN", hint: "Four sisters grow up during the Civil War" },
    { word: "LORD OF THE FLIES", hint: "Boys become savages on a deserted island" },
    { word: "LOVE IN THE TIME OF CHOLERA", hint: "A love story spanning decades" },
    { word: "MACBETH", hint: "A tragedy about ambition and murder" },
    { word: "MADAME BOVARY", hint: "A woman's search for romance leads to ruin" },
    { word: "MOBY DICK", hint: "A captain hunts a giant white whale" },
    { word: "NINETEEN EIGHTY-FOUR", hint: "A dystopian novel about total surveillance" },
    { word: "OLIVER TWIST", hint: "A young orphan survives in Victorian London" },
    { word: "ONE HUNDRED YEARS OF SOLITUDE", hint: "A family saga in a magical village" },
    { word: "OTHELLO", hint: "A tragedy about jealousy and betrayal" },
    { word: "PRIDE AND PREJUDICE", hint: "A novel about love, social class, and misunderstandings" },
    { word: "QUENTIN DURWARD", hint: "A historical novel by Walter Scott" },
    { word: "ROBINSON CRUSOE", hint: "A man survives alone on a desert island" },
    { word: "ROMEO AND JULIET", hint: "A tragic love story of two young lovers" },
    { word: "SHERLOCK HOLMES", hint: "The world's most famous detective" },
    { word: "THE CATCHER IN THE RYE", hint: "A teenager's disillusionment with society" },
    { word: "THE GREAT GATSBY", hint: "A story of wealth, love, and the American Dream" },
    { word: "THE HUNGER GAMES", hint: "Teenagers fight in a deadly arena" },
    { word: "THE MARTIAN", hint: "An astronaut survives alone on Mars" },
    { word: "THE OLD MAN AND THE SEA", hint: "A fisherman fights a giant fish" },
    { word: "THE SCARLET LETTER", hint: "A woman is shamed for adultery" },
    { word: "THE STAND", hint: "A novel about a global pandemic" },
    { word: "THE TEMPEST", hint: "A play about magic and revenge" },
    { word: "THE WIZARD OF OZ", hint: "A girl travels to a magical land" },
    { word: "TO KILL A MOCKINGBIRD", hint: "A novel about racial injustice in the American South" },
    { word: "ULYSSES", hint: "James Joyce's complex novel about a single day in Dublin" },
    { word: "VANITY FAIR", hint: "A satirical novel about social climbing" },
    { word: "WALDEN", hint: "A book about simple living in nature" },
    { word: "WAR AND PEACE", hint: "A monumental novel about the Napoleonic Wars" },
    { word: "WUTHERING HEIGHTS", hint: "A dark love story set on the moors" },
    { word: "XENIA", hint: "A novel about hospitality and strangers" },
    { word: "YEAR ZERO", hint: "A novel about the dawn of time" },
    { word: "ZEITGEIST", hint: "A novel about cultural change" },

    // --- 351-400: Movies & Films ---
    { word: "A BEAUTIFUL MIND", hint: "A film about a genius mathematician with schizophrenia" },
    { word: "ALIEN", hint: "A sci-fi film about a deadly space creature" },
    { word: "AVATAR", hint: "A film about a blue alien world and environmental themes" },
    { word: "BACK TO THE FUTURE", hint: "A film about time travel and a teenager" },
    { word: "BATMAN BEGINS", hint: "The origin story of the Dark Knight" },
    { word: "BEN-HUR", hint: "A historical epic about a Jewish prince" },
    { word: "BLADE RUNNER", hint: "A film about androids and what makes humans human" },
    { word: "BRAVEHEART", hint: "A film about Scottish independence and freedom" },
    { word: "BREAKFAST AT TIFFANY'S", hint: "A film about a free-spirited woman in New York" },
    { word: "BRIDGE ON THE RIVER KWAI", hint: "A war film about prisoners building a bridge" },
    { word: "CASABLANCA", hint: "A classic film about love and sacrifice during WWII" },
    { word: "CHINATOWN", hint: "A noir film about corruption in Los Angeles" },
    { word: "DANCES WITH WOLVES", hint: "A film about a soldier who befriends Native Americans" },
    { word: "DIE HARD", hint: "A film about a cop battling terrorists in a skyscraper" },
    { word: "DRIVE", hint: "A film about a stunt driver with a dark side" },
    { word: "E.T. THE EXTRA-TERRESTRIAL", hint: "A film about a boy who befriends an alien" },
    { word: "ESCAPE FROM ALCATRAZ", hint: "A film about prisoners escaping an island prison" },
    { word: "EVERYTHING EVERYWHERE ALL AT ONCE", hint: "A film about multiverses and family" },
    { word: "GLADIATOR", hint: "A film about a Roman general who becomes a gladiator" },
    { word: "GONE WITH THE WIND", hint: "A film about the American Civil War" },
    { word: "GOODFELLAS", hint: "A film about the mob and crime in New York" },
    { word: "GRAVITY", hint: "A film about astronauts stranded in space" },
    { word: "GROUNDHOG DAY", hint: "A film about a man reliving the same day" },
    { word: "HARRY POTTER AND THE PHILOSOPHER'S STONE", hint: "A young wizard discovers his powers" },
    { word: "HEAT", hint: "A crime film about a detective and a thief" },
    { word: "INCEPTION", hint: "A film about entering dreams to steal ideas" },
    { word: "INDIANA JONES", hint: "A film about an archaeologist and adventure" },
    { word: "IT'S A WONDERFUL LIFE", hint: "A film about a man who sees what life would be without him" },
    { word: "JAWS", hint: "A film about a killer shark and a small town" },
    { word: "JURASSIC PARK", hint: "A film about cloned dinosaurs and a park" },
    { word: "KING KONG", hint: "A film about a giant ape and a beauty" },
    { word: "LA LA LAND", hint: "A musical film about love and dreams in Hollywood" },
    { word: "LAWRENCE OF ARABIA", hint: "A film about a British officer in the desert" },
    { word: "LORD OF THE RINGS: THE FELLOWSHIP OF THE RING", hint: "A fantasy film about a ring and a quest" },
    { word: "MAD MAX: FURY ROAD", hint: "A film about a post-apocalyptic road war" },
    { word: "MATRIX", hint: "A film about a simulated reality and a hero" },
    { word: "MONEYBALL", hint: "A film about using statistics in baseball" },
    { word: "MOONLIGHT", hint: "A film about a boy growing up in Miami" },
    { word: "NO COUNTRY FOR OLD MEN", hint: "A film about a killer and a suitcase of money" },
    { word: "PAN'S LABYRINTH", hint: "A film about a girl and a magical underworld" },
    { word: "PARASITE", hint: "A film about class conflict in South Korea" },
    { word: "PULP FICTION", hint: "A film about interconnected stories of crime" },
    { word: "PYRAMID", hint: "A film about an ancient Egyptian tomb" },
    { word: "QUENTIN TARANTINO'S INGLOURIOUS BASTERDS", hint: "A film about soldiers hunting Nazis" },
    { word: "RAGING BULL", hint: "A film about a boxer's rise and fall" },
    { word: "REAR WINDOW", hint: "A film about a man spying from his window" },
    { word: "ROCKY", hint: "A film about an underdog boxer" },
    { word: "SAVING PRIVATE RYAN", hint: "A war film about saving a soldier" },
    { word: "SCHINDLER'S LIST", hint: "A film about a man who saved Jews during the Holocaust" },
    { word: "SHAWSHANK REDEMPTION", hint: "A film about friendship and escape from prison" },
    { word: "SILENCE OF THE LAMBS", hint: "A film about a detective and a cannibal" },
    { word: "SIXTH SENSE", hint: "A film about a boy who sees dead people" },
    { word: "SPIRITED AWAY", hint: "An anime film about a girl in a spirit world" },
    { word: "STAR WARS: A NEW HOPE", hint: "A space epic about a hero's journey" },
    { word: "TAXI DRIVER", hint: "A film about a lonely taxi driver in New York" },
    { word: "THE BOY WHO HARNESSED THE WIND", hint: "A film about a boy who builds a windmill" },
    { word: "THE DARK KNIGHT", hint: "A film about Batman and his greatest enemy" },
    { word: "THE GODFATHER", hint: "A film about a mafia family" },
    { word: "THE GOOD, THE BAD AND THE UGLY", hint: "A Western film about three gunslingers" },
    { word: "THE LION KING", hint: "An animated film about a lion prince" },
    { word: "THE MALTESE FALCON", hint: "A detective film about a valuable statue" },
    { word: "THE PRINCESS BRIDE", hint: "A film about adventure, love, and a hero" },
    { word: "THE PROFESSIONAL", hint: "A film about a hitman and a young girl" },
    { word: "THE SEARCHERS", hint: "A Western film about a man searching for a girl" },
    { word: "THE TERMINATOR", hint: "A film about a cyborg sent back in time" },
    { word: "THE THING", hint: "A horror film about a shape-shifting alien" },
    { word: "THE WIZARD OF OZ", hint: "A musical film about a girl in a magical land" },
    { word: "THE WRONG MAN", hint: "A film about a man wrongly accused of a crime" },
    { word: "TOY STORY", hint: "An animated film about toys that come to life" },
    { word: "UNFORGIVEN", hint: "A Western film about a retired killer" },
    { word: "V FOR VENDETTA", hint: "A film about a masked rebel fighting a regime" },
    { word: "VERTIGO", hint: "A film about obsession and deception" },
    { word: "WALL STREET", hint: "A film about greed and finance" },
    { word: "WARRIOR", hint: "A film about two brothers fighting in MMA" },
    { word: "WHIPLASH", hint: "A film about a drummer and a demanding teacher" },
    { word: "XANADU", hint: "A musical film about a roller disco and a muse" },
    { word: "YEAR OF THE DRAGON", hint: "A crime film about a police captain in Chinatown" },
    { word: "ZERO DARK THIRTY", hint: "A film about the hunt for Bin Laden" },
    { word: "ZOOLANDER", hint: "A comedy film about a fashion model" },

    // --- 451-500: More Words, Phrases & Final Items ---
    { word: "A DIME A DOZEN", hint: "Very common and easily found" },
    { word: "A FAT CHANCE", hint: "Very little or no chance" },
    { word: "ALL HANDS ON DECK", hint: "Everyone needed to help in an emergency" },
    { word: "BACK TO THE DRAWING BOARD", hint: "To start over because a plan failed" },
    { word: "BACKSEAT DRIVER", hint: "A passenger who gives unwanted advice" },
    { word: "CALL A SPADE A SPADE", hint: "To speak plainly and truthfully" },
    { word: "DIG YOUR OWN GRAVE", hint: "To cause your own failure or downfall" },
    { word: "DROP THE BALL", hint: "To fail to do something important" },
    { word: "END OF THE ROAD", hint: "The final point of a journey or process" },
    { word: "FOOL'S GOLD", hint: "Something that looks valuable but is not" },
    { word: "GO WITH THE FLOW", hint: "To accept what happens without resistance" },
    { word: "HEARD IT THROUGH THE GRAPEVINE", hint: "To learn something from rumors or gossip" },
    { word: "JOIN THE CLUB", hint: "To be in the same situation as others" },
    { word: "KNOCK ON WOOD", hint: "To avoid bad luck by touching wood" },
    { word: "MISS THE MARK", hint: "To fail to achieve the intended goal" },
    { word: "QUEEN'S ENGLISH", hint: "Proper, correct English language" },
    { word: "VERBAL TICK", hint: "An unintentional repetitive word or phrase" },
    { word: "XRAY VISION", hint: "The ability to see through objects (mythical)" },
    { word: "YOUR GUESS IS AS GOOD AS MINE", hint: "We both don't know the answer" },
    { word: "ZERO SUM GAME", hint: "A situation where one person's gain is another's loss" },
    { word: "A BIRD IN THE HAND", hint: "Better to have a small certainty than a large possibility" },
    { word: "A ROLLING STONE", hint: "A person who is constantly moving and restless" },
    { word: "BETTER SAFE THAN SORRY", hint: "Be cautious to avoid regret" },
    { word: "CURIOSITY KILLED THE CAT", hint: "Prying can lead to trouble" },
    { word: "DON'T COUNT YOUR CHICKENS", hint: "Don't assume success before it happens" },
    { word: "EVERY DOG HAS ITS DAY", hint: "Everyone will have good luck" },
    { word: "FULL OF HOT AIR", hint: "Talkative but lacking substance" },
    { word: "GREAT MINDS THINK ALIKE", hint: "Smart people often share ideas" },
    { word: "HINDSIGHT IS 20/20", hint: "Past events are easier to understand later" },
    { word: "IGNORANCE IS BLISS", hint: "Not knowing problems is a relief" },
    { word: "JACK OF ALL TRADES", hint: "Good at many things but not an expert" },
    { word: "KNOWLEDGE IS POWER", hint: "Understanding gives you control" },
    { word: "LAUGHTER IS THE BEST MEDICINE", hint: "Humor helps heal stress" },
    { word: "MONEY CAN'T BUY HAPPINESS", hint: "Wealth does not guarantee joy" },
    { word: "NO PAIN, NO GAIN", hint: "Effort is needed for success" },
    { word: "OPPORTUNITY KNOCKS ONCE", hint: "Don't miss a rare chance" },
    { word: "PRACTICE MAKES PERFECT", hint: "Repeated effort leads to mastery" },
    { word: "QUIET WATERS RUN DEEP", hint: "Calm people often have deep thoughts" },
    { word: "ROME WASN'T BUILT IN A DAY", hint: "Great things take time" },
    { word: "STRIKE WHILE THE IRON IS HOT", hint: "Act at the right moment" },
    { word: "THE EARLY BIRD CATCHES THE WORM", hint: "Start early to gain an advantage" },
    { word: "THE PEN IS MIGHTIER THAN THE SWORD", hint: "Words have more power than violence" },
    { word: "UNITY IS STRENGTH", hint: "Together, people are stronger" },
    { word: "VARIETY IS THE SPICE OF LIFE", hint: "Diversity makes life interesting" },
    { word: "WHEN IN ROME", hint: "Follow local customs" },
    { word: "WHERE THERE'S A WILL THERE'S A WAY", hint: "Determination overcomes obstacles" },
    { word: "XENIA", hint: "A concept of hospitality to strangers" },
    { word: "YOU CAN'T HAVE YOUR CAKE AND EAT IT TOO", hint: "Cannot have two incompatible things" },
    { word: "ZERO HOUR", hint: "The time when a critical event begins" },
    { word: "ZEITGEIST", hint: "The spirit of a particular time period" },
];
