const SECRET_WORDS_EN = [
    // ==================== 100 ENGLISH WORDS & PHRASES ====================
    { word: "AMBIVALENT", hint: "Having mixed feelings about something" },
    { word: "IGNORAMUS", hint: "An ignorant or stupid person" },
    { word: "NONCHALANT", hint: "Casually unconcerned or indifferent" },
    { word: "SERENDIPITY", hint: "Finding something good without looking for it" },
    { word: "EPHEMERAL", hint: "Lasting for a very short time" },
    { word: "QUINTESSENTIAL", hint: "The purest and most perfect example" },
    { word: "DISPARATE", hint: "Essentially different or distinct" },
    { word: "OBFUSCATE", hint: "To deliberately make something unclear" },
    { word: "PERFIDIOUS", hint: "Deceitful and untrustworthy" },
    { word: "MISANTHROPE", hint: "Someone who dislikes people in general" },
    { word: "CACOPHONY", hint: "A harsh, discordant mixture of sounds" },
    { word: "DIAPHANOUS", hint: "Light, delicate, and translucent" },
    { word: "EQUIVOCATE", hint: "To speak in a way that avoids commitment" },
    { word: "FLIBBERTIGIBBET", hint: "A silly, flighty, or scatterbrained person" },
    { word: "GRANDILOQUENT", hint: "Using lofty, pompous language" },
    { word: "HUBRIS", hint: "Excessive pride or self-confidence" },
    { word: "INNUENDO", hint: "An indirect or subtle suggestion" },
    { word: "JUXTAPOSITION", hint: "Placing two things side by side for contrast" },
    { word: "KALEIDOSCOPE", hint: "A constantly changing pattern of colors and shapes" },
    { word: "LACONIC", hint: "Using very few words, concise" },
    { word: "MALADROIT", hint: "Clumsy or awkward in action" },
    { word: "NEBULOUS", hint: "Vague, unclear, or ill-defined" },
    { word: "OBDURATE", hint: "Stubbornly persistent in refusing to change" },
    { word: "PANTHEON", hint: "A temple dedicated to all gods; a group of revered figures" },
    { word: "QUIXOTIC", hint: "Excessively idealistic and unrealistic" },
    { word: "RECALCITRANT", hint: "Defiant of authority or control" },
    { word: "SALIENT", hint: "Most noticeable or important" },
    { word: "TANTAMOUNT", hint: "Equivalent in value or effect" },
    { word: "UBIQUITOUS", hint: "Present, appearing, or found everywhere" },
    { word: "VICISSITUDE", hint: "A change of circumstances, often unwelcome" },
    { word: "WISTFUL", hint: "Longing with a tinge of sadness" },
    { word: "XENOPHOBIA", hint: "Fear or hatred of foreigners or strangers" },
    { word: "YESTERYEAR", hint: "The past, especially a time long ago" },
    { word: "ZEALOT", hint: "A person who is fanatical and uncompromising" },
    { word: "ABRACADABRA", hint: "A magical word used to perform tricks" },
    { word: "BALLYHOO", hint: "Extravagant publicity or fuss" },
    { word: "CANTANKEROUS", hint: "Bad-tempered, argumentative, and uncooperative" },
    { word: "DALLIANCE", hint: "A casual or flirtatious relationship" },
    { word: "ELUSIVE", hint: "Difficult to find, catch, or achieve" },
    { word: "FACETIOUS", hint: "Flippant or joking, often inappropriately" },
    { word: "GARRULOUS", hint: "Excessively talkative, especially on trivial matters" },
    { word: "HAPLESS", hint: "Unlucky; unfortunate" },
    { word: "INCIDENTAL", hint: "Less important; happening as a minor consequence" },
    { word: "JOVIAL", hint: "Cheerful and friendly" },
    { word: "KNAVE", hint: "A dishonest or unscrupulous man" },
    { word: "LETHARGIC", hint: "Sluggish, apathetic, or drowsy" },
    { word: "MENDACIOUS", hint: "Untruthful; given to lying" },
    { word: "NOXIOUS", hint: "Harmful, poisonous, or offensive" },
    { word: "OBSEQUIOUS", hint: "Obedient, attentive, and fawning" },
    { word: "PALLIATE", hint: "To make a problem less severe without curing it" },
    { word: "QUAGMIRE", hint: "A difficult situation; a soft, boggy area" },
    { word: "RUSTIC", hint: "Relating to the countryside; simple and unsophisticated" },
    { word: "SPURIOUS", hint: "Fake; not genuine" },
    { word: "TRITE", hint: "Overused and lacking originality" },
    { word: "UNCTUOUS", hint: "Excessively flattering or ingratiating" },
    { word: "VACILLATE", hint: "Waver between different opinions or actions" },
    { word: "WARY", hint: "Cautious and watchful" },
    { word: "XENIAL", hint: "Friendly or hospitable to strangers" },
    { word: "YAWL", hint: "A small sailing boat; to make a loud cry" },
    { word: "ZIGZAG", hint: "Move in sharp turns from side to side" },
    { word: "A BIRD IN THE HAND", hint: "Better to have a small certainty than a large possibility" },
    { word: "BARKING UP THE WRONG TREE", hint: "Mistakenly directing efforts at the wrong target" },
    { word: "COLD FEET", hint: "Nervousness before an important event" },
    { word: "DON'T COUNT YOUR CHICKENS", hint: "Don't assume success before it happens" },
    { word: "EVERY CLOUD HAS A SILVER LINING", hint: "There is something good in every bad situation" },
    { word: "FULL OF HOT AIR", hint: "Talkative but lacking substance" },
    { word: "GO THE EXTRA MILE", hint: "Make more effort than expected" },
    { word: "HOLD YOUR HORSES", hint: "Wait a moment; slow down" },
    { word: "IT TAKES TWO TO TANGO", hint: "Both parties are needed for a situation" },
    { word: "JUMP ON THE BANDWAGON", hint: "Join a trend or popular movement" },
    { word: "KEEP YOUR CHIN UP", hint: "Stay optimistic and strong" },
    { word: "LET THE CAT OUT OF THE BAG", hint: "Reveal a secret by accident" },
    { word: "MAKE A MOUNTAIN OUT OF A MOLEHILL", hint: "Exaggerate a minor problem" },
    { word: "NEVER BITE THE HAND THAT FEEDS YOU", hint: "Don't harm someone who helps you" },
    { word: "ONCE IN A BLUE MOON", hint: "Very rarely" },
    { word: "PULL SOMEONE'S LEG", hint: "Tease or joke with someone" },
    { word: "QUICK ON THE DRAW", hint: "Fast to react or respond" },
    { word: "RUB SOMEONE THE WRONG WAY", hint: "Irritate or annoy someone" },
    { word: "SPILL THE BEANS", hint: "Reveal secret information" },
    { word: "THE BALL IS IN YOUR COURT", hint: "It is your turn to take action" },
    { word: "UNDER THE WEATHER", hint: "Feeling ill or unwell" },
    { word: "VANITY FAIR", hint: "A place of shallow, superficial glamour" },
    { word: "WALK ON EGGSHELLS", hint: "Act with extreme caution around someone" },
    { word: "X MARKS THE SPOT", hint: "The exact location of something" },
    { word: "YOU CAN'T TEACH AN OLD DOG NEW TRICKS", hint: "Older people find it hard to change" },
    { word: "ZERO HOUR", hint: "The time when an important event begins" },
    { word: "ALL THAT GLITTERS IS NOT GOLD", hint: "Appearances can be deceptive" },
    { word: "BETTER LATE THAN NEVER", hint: "It's better to arrive late than not at all" },
    { word: "CURIOSITY KILLED THE CAT", hint: "Prying into things can lead to trouble" },
    { word: "DON'T PUT ALL YOUR EGGS IN ONE BASKET", hint: "Don't risk everything on one venture" },
    { word: "EVERY DOG HAS ITS DAY", hint: "Everyone will have a lucky moment" },
    { word: "FOR BETTER OR FOR WORSE", hint: "In good times and bad" },
    { word: "GREAT MINDS THINK ALIKE", hint: "Smart people often have the same ideas" },
    { word: "HINDSIGHT IS 20/20", hint: "Understanding past events is easier after they happen" },
    { word: "IGNORANCE IS BLISS", hint: "Not knowing problems is a relief" },
    { word: "JACK OF ALL TRADES, MASTER OF NONE", hint: "Good at many things, expert at none" },
    { word: "KNOWLEDGE IS POWER", hint: "Understanding gives you control" },
    { word: "LAUGHTER IS THE BEST MEDICINE", hint: "Humor helps heal stress and sadness" },
    { word: "MONEY CAN'T BUY HAPPINESS", hint: "Wealth does not guarantee joy" },
    { word: "NO PAIN, NO GAIN", hint: "Effort and struggle are needed for success" },
    { word: "OPPORTUNITY KNOCKS ONLY ONCE", hint: "Don't miss a rare chance" },
    { word: "PRACTICE MAKES PERFECT", hint: "Repeated effort leads to mastery" },
    { word: "QUIET WATERS RUN DEEP", hint: "Calm people often have deep thoughts" },
    { word: "ROME WASN'T BUILT IN A DAY", hint: "Great things take time" },
    { word: "STRIKE WHILE THE IRON IS HOT", hint: "Act at the right moment" },
    { word: "THE EARLY BIRD CATCHES THE WORM", hint: "Start early to gain an advantage" },
    { word: "UNITY IS STRENGTH", hint: "Together, people are stronger" },
    { word: "VARIETY IS THE SPICE OF LIFE", hint: "Change and diversity make life interesting" },
    { word: "WHERE THERE'S A WILL, THERE'S A WAY", hint: "Determination overcomes obstacles" },
    { word: "YOU CAN'T HAVE YOUR CAKE AND EAT IT TOO", hint: "Cannot have two incompatible things" },
];
